# -*- coding: utf-8 -*-
"""first python code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NdsrV9xxdXz4YPobFkTKDMjZev6WrWv-

# welcome to python

### introducing the print function
"""

print("hello world!!")

print("my name is rachael")

print("i'm learning about githb and i'm going add my work to a repository i cloned")

